version: '3.8'
services:
  database:
    image: 'mongo'
    container_name: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongoDB:/data/db
    ports:
      - '27017:27017'
    logging:
      options:
        max-size: '10m'
        max-file: '3'
